# The Base URL to the REST API service
#
# Sandbox environment (recommended, free of charge):
api_base_url: "https://api.cloud.wowza.com"
#
# Live Environment (NOT free of charge!):
# api_base_url: "https://api.cloud.wowza.com"

# The version of the API (currently there is only version 1)
api_version: "v1"

# Enable debugging (set to 'true') to see header responses and response codes
debug: false
